import { createServiceClient } from "@/lib/supabase/server";
import { formatDate } from "@/lib/utils";

/**
 * Client portal — accessed via signed link (no login).
 * Token is generated by CA firm; expires in 30 days unless renewed.
 *
 * v1: read-only view of client's status, notices, filings.
 * v2: add OTP verification on first open + watermark with phone number.
 */
export default async function ClientPortalPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const supabase = createServiceClient();

  const { data: portalToken } = await supabase
    .from("client_portal_tokens")
    .select("*, clients(name, primary_contact_name)")
    .eq("token", token)
    .single();

  if (!portalToken || new Date(portalToken.expires_at) < new Date()) {
    return (
      <main className="mx-auto max-w-md px-6 py-20 text-center">
        <h1 className="text-2xl font-bold text-red-700">Link expired or invalid</h1>
        <p className="mt-4 text-ink-600">Please ask your CA to share a new link.</p>
      </main>
    );
  }

  const client = (portalToken as { clients?: { name: string; primary_contact_name: string } }).clients;

  const { data: openNotices } = await supabase
    .from("notices")
    .select("notice_type, deadline, demand_amount, status")
    .eq("client_id", portalToken.client_id)
    .neq("status", "closed")
    .order("deadline", { ascending: true });

  return (
    <main className="mx-auto max-w-2xl px-6 py-12">
      <header className="mb-8 rounded-xl border border-ink-200 bg-white p-6">
        <h1 className="text-2xl font-bold">{client?.name}</h1>
        <p className="text-ink-600">Hello {client?.primary_contact_name || "client"}, here's your latest status.</p>
      </header>

      <section className="mb-6 rounded-xl border border-ink-200 bg-white p-6">
        <h2 className="font-bold">Open GST notices ({openNotices?.length || 0})</h2>
        {!openNotices || openNotices.length === 0 ? (
          <p className="mt-2 text-sm text-ink-600">No open notices. All clear ✓</p>
        ) : (
          <ul className="mt-3 space-y-3">
            {openNotices.map((n, i) => (
              <li key={i} className="rounded-lg border border-ink-100 p-3">
                <div className="font-medium">{n.notice_type}</div>
                <div className="text-xs text-ink-500">
                  {n.deadline && `Deadline: ${formatDate(n.deadline)} · `}
                  Status: {n.status}
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>

      <p className="text-center text-xs text-ink-500">
        Powered by NotusAI · For questions, contact your CA directly.
      </p>
    </main>
  );
}
